## Basic set of questions


In [1]:
import numpy as np

##### Q1. Creating a 2D array of shape (3,4) filled with numbers from 0 to 11.

In [5]:
arr_2d = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
print(arr_2d)

arr_2d = np.arange(0,12)
result = arr_2d.reshape(3,4)
print(result)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Q2. Replace all even numbers in an array with -1.

In [19]:
arr = np.array([10, 2, 3, 4, 5])
arr[arr % 2 == 0] = -1
print(arr)

[-1 -1  3 -1  5]


### Q3. Given arr = np.array([1,2,3,4,5]), convert it into a column vector of shape (5,1).

In [4]:
arr = np.array([1,2,3,4,5])
result = np.reshape(arr,(5,1))
print(result)

[[1]
 [2]
 [3]
 [4]
 [5]]



### Q4. Create an array of 10 random integers between 1 and 100.

In [9]:
arr = np.random.randint(1, 101, size=10)
print(arr)

[57 67 77 93 69 80  1 85 45 58]


### Q5. Extract all elements at odd indices from a 1D array.

In [13]:
arr = np.array([0,1,2,3,4,5,6,7,8,9,10])
print(arr[1::2])  

[1 3 5 7 9]


### Q6. Create an array of numbers from 1 to 20 and extract only the multiples of 3.

In [ ]:
arr = np.arange(1,21)
print(arr[arr %3 == 0])

[ 3  6  9 12 15 18]


### Q7. Given arr = np.array([5, 10, 15, 20, 25, 30]), replace all values greater than 15 with 999.


In [24]:
arr = np.array([5, 10, 15, 20, 25, 30])
arr[arr>15] = 999
print(arr)

[  5  10  15 999 999 999]


### Q8. Create a 2D array with shape (4,4) where the diagonal contains values 10, 20, 30, 40.

### Q9. From the array
### A = [[1, 2, 3],
###      [4, 5, 6],
###      [7, 8, 9]]
### extract the corner values: 1, 3, 7, 9.

In [ ]:
A = np.array([[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])


### Q10. Create a 1D array of 10 random integers between 0–50 and replace numbers between 10 and 20 (inclusive) with -5.

In [10]:
arr = np.random.randint(0,51, size = 10)
arr[(arr<=20) & (arr>=10)] = -5
print(arr)

[44  6 -5 50 -5 37 -5 40  7 -5]


### Q11. Convert np.arange(9) into a 3×3 matrix without using reshape().

In [17]:
arr = np.arange(9)
result = np.split(arr,3)
print(np.array(result))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Q12. Reverse a 1D NumPy array using slicing.


In [18]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr[::-1])

[10  9  8  7  6  5  4  3  2  1]


### Q13. Swap row 0 and row 2 in a 3×3 array without using loops.


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
result = arr.reshape(3,3)
result[[0, 2]] = result[[2, 0]]
print(result)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


### Q14. Create a (3,5) array of random integers and set the minimum value of each column to 0.


### Q15. Count how many numbers in a random array of size 100 are divisible by both 2 and 5.

In [37]:
arr = np.random.randint(1, 101, size=100)
count = np.sum((arr % 2 == 0) & (arr % 5 == 0))
print(count)

10
