In [1]:
import numpy as np

### 1. Reshape a 1D array of length 8 into shape (2, 2, 2).


In [3]:
A = np.arange(1,9)
print(A.reshape(2,2,2))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### 2. Using broadcasting and reshape, create a multiplication table from 1 to 10.


In [ ]:
a = np.arange(1, 11)
table = a.reshape(-1, 1) * a #here -1 infers the number of rows automatically and 1 is for single column
print(table)
#instead of telling NumPy exactly how many rows, you say:
#“NumPy, you decide how many rows are needed.
#I just want 1 element in each row.”

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


### 3. Given a 2D array, replace each row with its mean using vectorized operations (no loops).


In [9]:
arr = np.array([[1,2,3],
                [4,5,6]])
arr[:] = arr.mean(axis=1, keepdims=True)
print(arr)

[[2 2 2]
 [5 5 5]]


### 4. Check whether ravel() returns a view or a copy for:
### a = np.arange(10)[::2]


In [ ]:
a = np.arange(10)[::2]
r = a.ravel()
r[-1] = 999
print(a)   # original array remains unchanged
print(r)   # first element changed to 999


[0 2 4 6 8]
[  0   2   4   6 999]


### 5. Create a 5×5 identity matrix and replace its diagonal with values from 1 to 5.


In [26]:
arr = np.eye(5)
print(arr)
np.fill_diagonal(arr, np.arange(1,6))
print("replaced diagonal elements: \n",arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
replaced diagonal elements: 
 [[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


### 6. Given a 3D array of shape (2, 3, 4), extract the second slice along axis 0.


In [29]:
arr = np.arange(24).reshape(2, 3, 4)
print(arr[1])

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


### 7. Create a random 2D array and normalize each column so that its values sum to 1.


In [35]:
arr = np.arange(1, 9).reshape(2, 4)
print(arr / arr.sum(axis=0))


[[0.16666667 0.25       0.3        0.33333333]
 [0.83333333 0.75       0.7        0.66666667]]


### 8. Without using loops, find the index of the maximum value in each row of a 2D array.


In [40]:
arr = np.array([[10,3,2],
                [4,43,6]])
print(np.argmax(arr, axis=1))

[0 1]


### 9. Given two arrays of shapes (5,1) and (1,5), compute their outer sum using broadcasting.


In [44]:
A = np.arange(1,6).reshape(5,1)
B = np.arange(6,11).reshape(1,5)
print(A+B)  # or A[:, None] + B[None, :]

[[ 7  8  9 10 11]
 [ 8  9 10 11 12]
 [ 9 10 11 12 13]
 [10 11 12 13 14]
 [11 12 13 14 15]]


### 10. Convert a 2D array into a 1D array without using flatten() or ravel().


In [ ]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr.reshape(-1))  # here -1 flattens the array into 1D array

[1 2 3 4 5 6]


### 11. Given a 2D array, subtract the row-wise mean from each element (mean centering).


In [46]:
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr - arr.mean(axis=1, keepdims=True))

[[-1.  0.  1.]
 [-1.  0.  1.]]


### 12. From a 3D array, extract all elements greater than a given threshold using boolean masking.


In [56]:

arr_3d = np.random.randint(0, 100, size=(3, 4, 5))
threshold = 50
result_12 = arr_3d[arr_3d > threshold]
print("12:", result_12)


12: [60 62 51 98 88 63 97 51 68 92 54 98 55 94 61 97 98 97 57 72 90 84 76 61
 70 86 55 61]


### 13. Create a checkerboard pattern (alternating 0s and 1s) of shape (8, 8).


In [ ]:

checkerboard = np.indices((8, 8)).sum(axis=0) % 2
print("13:\n", checkerboard)


### 14. Given a 2D array, replace all values below the 25th percentile with 0.


In [55]:

arr_2d = np.random.randint(0, 100, size=(5, 5))
p25 = np.percentile(arr_2d, 25)
arr_2d[arr_2d < p25] = 0
print("14:\n", arr_2d)


14:
 [[92  0 85 86 89]
 [32  0  0 63 68]
 [57 27 34  0 28]
 [ 0 66 97 36 64]
 [82 46 35  0 95]]


### 15. Stack three 2D arrays of shape (3, 3) into a single 3D array.


In [54]:

a = np.ones((3, 3))
b = np.zeros((3, 3))
c = np.full((3, 3), 5)
stacked_3d = np.stack((a, b, c))
print("15 shape:", stacked_3d.shape)


15 shape: (3, 3, 3)


### 16. Given a large NumPy array, compare the execution time of a vectorized operation vs a Python loop.


In [53]:

large_arr = np.random.rand(1_000_000)

%timeit large_arr * 2

%timeit [x * 2 for x in large_arr]



5.12 ms ± 777 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
453 ms ± 109 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### 17. Using NumPy only, compute the cumulative sum along axis 1 of a 2D array.


In [52]:

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
cumsum_axis1 = np.cumsum(arr, axis=1)
print("17:\n", cumsum_axis1)



17:
 [[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


### 18. Given a 2D array, find the indices of elements that satisfy two conditions simultaneously.


In [51]:

arr = np.random.randint(0, 100, size=(5, 5))
indices = np.where((arr > 30) & (arr < 70))
print( indices)


(array([0, 1, 1, 2, 2, 2, 3, 3, 4]), array([4, 0, 2, 0, 2, 4, 0, 2, 3]))


### 19. Create a sliding window view of size (3,) over a 1D array.


In [58]:
from numpy.lib.stride_tricks import sliding_window_view

arr_1d = np.arange(10)
windows = sliding_window_view(arr_1d, 3)

print(windows)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


### 20. Given two arrays of equal shape, compute the cosine similarity row-wise using vectorized NumPy operations.

In [47]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[1, 0, 1],
              [0, 1, 0],
              [1, 1, 1]])

dot = np.sum(A * B, axis=1)
norms = np.linalg.norm(A, axis=1) * np.linalg.norm(B, axis=1) # here linalg.norm computes the Euclidean norm (L2 norm) of each row
cosine_similarity = dot / norms
print("20:", cosine_similarity)

20: [0.75592895 0.56980288 0.99483201]
