### 1. Given
### arr = np.array([[10, 20, 30],
###                 [40, 50, 60],
###                 [70, 80, 90]])
### extract the middle column.

In [1]:
import numpy as np

In [ ]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
# print(arr[(0,1)], arr[(1,1)], arr[(2,1)])
print(arr[:, 1]) # here : is used to access all the rows and 1 is used to access the 2nd column of each row



[20 50 80]


### 2. From a 1D array of 15 elements, extract elements at indices divisible by 3.


In [ ]:
arr = np.random.randint(1, 16, size = 15)
print(arr)
indices = np.arange(len(arr))     
print(arr[indices % 3 == 0])

[ 2  3 14 14  4 11  3  1 15 14  7 11  5  4  8]
[ 2 14  3 14  5]


### 3. Split np.arange(16) into 4 equal sub-arrays.

In [ ]:
arr = np.arange(16)
print(arr)
print(np.array(np.split(arr, 4)))  # splits the array into 4 equal parts
# or
print(np.split(np.arange(16), 4))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11]), array([12, 13, 14, 15])]


### 4. Concatenate two arrays vertically (axis=0) where both have shape (2,3).

In [24]:
arr1 = np.array([[1, 2, 3],
                    [4, 5, 6]]) 
arr2 = np.array([[7, 8, 9],
                    [10, 11, 12]])
result = np.concatenate((arr1, arr2), axis=0)
print(result)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### 5. Given a 2D array, extract only the last row and keep it 2D (not flattened).


In [ ]:
arr_2d = np.array([[1, 2],
                   [3,4]])
print(arr_2d[1].reshape(2,1)) 
#or
print(arr_2d[-1:])
                    

[[3]
 [4]]
[[3 4]]


### 6. Using slicing only, reverse each row of a 2D array.

In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
result = arr_2d[:, ::-1] # here the first : is to access all rows and ::-1 is to reverse the columns
print(result)


[[3 2 1]
 [6 5 4]
 [9 8 7]]


### 7. Add a column vector [100, 200, 300] to every column of this array using broadcasting:
###      A = [[1, 2, 3],
###          [4, 5, 6],
###          [7, 8, 9]]

In [ ]:
A = np.array([[1, 2, 3],
       [4, 5, 6],
      [7, 8, 9]])
B = np.array([100, 200, 300]).reshape(3, 1) # reshaping B to be a column vector
result = A + B # Broadcasting will add B to each row of A
print(result)


[[101 102 103]
 [204 205 206]
 [307 308 309]]


### 8. From a random array of size 30, replace all numbers less than the mean with 0.



In [20]:
A = np.random.randint(1,31, size = 30)
A[A < A.mean()] = 0
print(A)

[22 16  0  0 20  0  0  0 28 25 28  0  0  0  0 15 19 16  0 26 24 22  0 18
  0 29  0  0  0 27]


### 9. Given a 2D array, count how many elements are greater than 50 using boolean masking.


In [ ]:
arr_2d = np.array([[35,58]
                   ,[12,45],
                   [78,89]])
count = np.sum(arr_2d > 50) # counts the number of elements greater than 50
print(count)

3


### 10. Convert a 1D array of length 12 into a (3,4) matrix without using reshape().


In [ ]:
arr = np.arange(12)
result = np.split(arr,3) # splits the array into 3 equal parts
print(np.array(result)) # CONVERTING INTO A NUMPY ARRAY FOR BETTER VISUALIZATION

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### 11. Swap column 0 and column 2 of a 2D array without loops.


In [34]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

arr_2d[:, [0, 2]] = arr_2d[:, [2, 0]]

print(arr_2d)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


### 12. Using NumPy only, find the row-wise sum of a 2D array.


In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                     [7, 8, 9]])
#row wise sum of the array
print(np.sum(arr_2d, axis = 1))
# solution ends here.
#column wise sum of the array(if you wanna know)
print(np.sum(arr_2d, axis = 0))


[ 6 15 24]
[12 15 18]


### 13. From a 2D array, extract all elements that are even.


In [40]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],   
                   [7, 8, 9]])
new = arr_2d.flatten()
print(new[new%2 == 0])

[2 4 6 8]


### 14. Create a (4,4) array and set the last column to 1 using slicing.


In [ ]:
arr = np.arange(16).reshape(4,4)
arr[: , -1] = 1 #here : is to access all the rows and -1 is to access the last column
print(arr)

[[ 0  1  2  1]
 [ 4  5  6  1]
 [ 8  9 10  1]
 [12 13 14  1]]


### 15. Given two arrays of shape (3,1) and (1,4), add them and print the resulting shape.


In [46]:
A = np.array([[1],
[2],
[3]])
B = np.array([[4],
[5],
[6]])
print(A + B)

[[5]
 [7]
 [9]]


### 16. Split the array np.arange(12) into 3 equal sub-arrays.


In [48]:
A = np.arange(12)
print(np.array(np.split(A,3)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### 17. Concatenate two 2D arrays horizontally (axis=1).


In [49]:
A = np.array([[1, 2, 3],
       [4, 5, 6],
        [7, 8, 9]])
B = np.array([[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]])
print(np.concatenate((A, B), axis=1))

[[1 2 3 9 8 7]
 [4 5 6 6 5 4]
 [7 8 9 3 2 1]]


### 18. Using broadcasting, add a row vector [10,20,30] to every row of a 2D array:
###      A = [[1,2,3],
###           [4,5,6],
###           [7,8,9]]


In [50]:
A = np.array([[1,2,3],
          [4,5,6],
         [7,8,9]])
B = np.array([10,20,30])
print(A + B)


[[11 22 33]
 [14 25 36]
 [17 28 39]]


### 19. Use boolean masking to extract all values > 50 from a random array of size 20.


In [54]:
A = np.random.randint(1,101, size = 20)
print(A[A>50])

[88 61 77 83 61 61 66 91 51]


### 20. Given arr = np.array([[1,2,3],[4,5,6]]), extract the second column.

In [59]:
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr[:, 1])

[2 5]
