## Basics in Arrays
#### Creating a 1D array
#### creating a 2-D array
#### Creating a 3D array (matrix)
#### creating arrays from python lists
#### creating arrays with default values
#### creating an array with zeros np.zeros(shape)
#### creating an array with ones np.ones(shape)
#### creating an array full of same value np.full(fill_value), np.full(shape, fill_value)-->for 2D
#### creating sequences of numbers in numpy #np.arange(start, stop, step)


In [3]:
import numpy as np

In [4]:
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:\n", array_1d)

1D Array:
 [1 2 3 4 5]


In [5]:
array_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
print("\n2D Array:\n", array_2d)


2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
array_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9],[10, 11, 12]],
    [[13, 14, 15],[16, 17, 18]]
                     ])
print("\n3D Array:\n", array_3d)


3D Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [9]:
arr = [10, 20, 30, 40, 50]
numpy_arr = np.array(arr)
print("The numpy array is ", numpy_arr)

The numpy array is  [10 20 30 40 50]


In [8]:
zeros_array = np.zeros((2, 3))
print("\nArray of Zeros:\n", zeros_array)

ones_array = np.ones((3, 2))
print("\nArray of Ones:\n", ones_array)

full_array = np.full((2, 4), 7)
print("\nArray Full of Sevens:\n", full_array)


Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Array of Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

Array Full of Sevens:
 [[7 7 7 7]
 [7 7 7 7]]


In [10]:
arange_array = np.arange(0, 10, 2) 
print("\nArray using arange:\n", arange_array)


Array using arange:
 [0 2 4 6 8]


In [11]:
#creating identity matices
identity_matrix = np.eye(3) #np.eye(n)
print("\nIdentity Matrix:\n", identity_matrix)


Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:

#creating random arrays
random_array = np.random.rand(2, 3) #np.random.rand(d0, d1, ..., dn)
print("\nRandom Array:\n", random_array)



Random Array:
 [[0.00449236 0.9590142  0.69740087]
 [0.28722379 0.48723679 0.66687185]]


In [13]:

#creating an array of 10 random integers between any two numbers
arr = np.random.randint(1, 51, size=10)
print(arr)

[26 45  1  7 44 10 15  6 17 12]
