## Properties and Operations
### Shape:  shape returns the dimensions of a NumPy array as a tuple, showing how many elements it has along each axis.
### Size:  it returns the number of elements.
### ndim:  ndim stands for no of dimentions. this attribute returns the number of dimentions of an array. 
### dtype:  data type is returned.
### the above attributes are used to check certain things about the array.
### astype:  this is an operation used to convert one datatype to another


##### Shape 

In [ ]:
import numpy as np

In [8]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.shape)

arr2 = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr2.shape)

arr3 = np.array([[[1, 2],[3, 4]], 
                [[5, 6],[7, 8]]])
                # the above list has 2 blocks, each block har 2 rows and two colomns hence 2x2x2
print(arr3)
print(arr3.shape)


(6,)
(2, 3)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


#### Size


In [9]:
print(arr.size)
print(arr2.size)
print(arr3.size)    

6
6
8


#### ndim

In [10]:
print(arr.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


#### dtype

In [11]:
arr4 = np.array([1, 2, 3, 4])
print(arr4.dtype)
arr5 = np.array(['apple', 'banana', 'cherry'])
print(arr5.dtype)
arr6 = np.array([1.5, 2.5, 3.5])
print(arr6.dtype)


int64
<U6
float64


#### astype
##### Syntax: array.astype(new_type)

In [13]:
arr_inttype = arr6.astype(int)
print(arr_inttype)
print(arr_inttype.dtype)

[1 2 3]
int64


### operations on numpy arrays can be easily done without using loops.
#### Arithmetic Operations: + , - , * , ** , / , // , %

In [16]:
math_arr = np.array([1,2,3,4,5])
print(math_arr + 2)
print(math_arr * 2)
print(math_arr / 2)
print(math_arr % 2)

[3 4 5 6 7]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[1 0 1 0 1]


#### Aggregate functions
##### sum, mean, min, max, standard deviation, varience.

In [19]:
arr = np.array([1,2,3,4,5])

print("the sum of elements: ", np.sum(arr))
print("the mean of elements: ", np.mean(arr))
print("the smallest of elements: ", np.min(arr))
print("the largest element: ", np.max(arr))
print("Standard deviation is: ", np.std(arr))
print("Varience is: ",np.var(arr))

the sum of elements:  15
the mean of elements:  3.0
the smallest of elements:  1
the largest element:  5
Standard deviation is:  1.4142135623730951
Varience is:  2.0
