## Array modification in numpy
##### we learn how to add, remove, stack and split an array
##### 1. Inserting
##### 2. appending
##### 3. concatenate
##### 4. Deleting
##### 5. Stacking and Splitting

# --------------------------------------------------------------

##### 1. Inserting
##### Syntax: np.insert(array_name, index_pos, value, axis=Noneor0or1)

In [2]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)
arr_1 = np.insert(arr, 2, 10)
print(arr_1)

[1 2 3 4 5 6]
[ 1  2 10  3  4  5  6]


In [14]:
arr_2d = np.array([[1,2],
                   [3,4]])
print(arr_2d)
arr_2d_1 = np.insert(arr_2d, 1, [5,6], axis=1)  # inserting row
print(arr_2d_1)

[[1 2]
 [3 4]]
[[1 5 2]
 [3 6 4]]


#### 2. appending
##### Syntax :- np.append(array_name, value)

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)
arr_1 = np.append(arr, [7, 8, 9])
print(arr_1)

[1 2 3 4 5 6]
[1 2 3 4 5 6 7 8 9]


In [4]:
arr_2d = np.array([[1,2],
                   [3,4]])
print(arr_2d)
arr_2d_1 = np.append(arr_2d,[5,6])  # inserting row
print(arr_2d_1)

[[1 2]
 [3 4]]
[1 2 3 4 5 6]


#### 3. Concatenate
##### Syntax: np.concatenate((array1, array2), axis = 0 or 1)

In [10]:
arr = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr_1 = np.concatenate((arr2, arr), axis = 0)
print(arr_1)

[4 5 6 1 2 3]


In [12]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

# Concatenate along columns
result = np.concatenate((a, b), axis=0)
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [11]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

# Concatenate along columns
result = np.concatenate((a, b), axis=1)
print(result)

[[1 2 5 6]
 [3 4 7 8]]


#### 4. Deleting
##### Syntax: np.delete(array_name, index)

In [13]:
arr = np.array([1, 2, 3])
arr_1 = np.delete(arr, 2)
print(arr_1)

[1 2]


In [ ]:
b = np.array([[5, 6],
              [7, 8]])

# Delete first column
result = np.delete(b, 0, axis=1)
print(result)

[[6]
 [8]]


#### 5. Stacking and Splitting
##### we have np.vstack(), np.hstack() for stacking and np.vsplit(), np.hsplit()
##### Syntax: For Stacking - .vstack(array1, array2) "vertical stacking" .hstack(array1, array2)"horizontal stacking"
#####         For Splitting - .vsplit(array_name, no of times to split) "vertical split" .hsplit()"horizontal split"

In [20]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])
result = np.hstack((a, b))
print(result)
result = np.vstack((a, b))
print(result)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [48]:
a = np.array([1, 2, 3, 4, 5, 6])
result_h = np.hsplit(a, 3)
print(result_h)
a = np.array([1, 2, 3, 4, 5, 6]).reshape(3, 2)
result_v = np.vsplit(a, 3)
print(result_v)


[array([1, 2]), array([3, 4]), array([5, 6])]
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
