# 1. Broadcasting:
#### Broadcasting lets NumPy do math on arrays of different sizes by stretching the smaller one automatically.
#### for example: 

In [2]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])# a is a 1D array with 3 elements
b = 5 # b is a scalar value(single number)

print(a + b) #adds 5 to each element in array a

[6 7 8]


In [4]:
A = np.array([[1, 2, 3],
              [4, 5, 6]]) # A is a 2D array with 2 rows and 3 columns

B = np.array([10, 20, 30]) # B is a 1D array with 3 elements

print(A + B) #adds B to each row of A

[[11 22 33]
 [14 25 36]]


## How NumPy handles different shaped arrays or rules
#### 1. Matching Dimentions : eg - [1, 2, 3] , [4, 5, 6] # same number of elements in both the arrays
#### 2. Expanding single elements : eg - a = [1, 2, 3], b = 5 # numpy adds 5 to each element in a (expansion) 
#### 3. Incompatible Shapes : eg - a = [10, 20, 30], b= [ 1, 2] # both the arrays are of different shapes 

# 2. Vectorization:
#### Vectorization in NumPy means performing operations on entire arrays at once without using loops, making calculations faster and more efficient.
#### for example:

In [10]:
a = np.array([1, 2, 3, 4])
result = a * 10
print(result)

[10 20 30 40]


In [ ]:
a = np.array([10, 20, 30, 40])
print(a > 25) # returns a boolean array 

[False False  True  True]
