#### Indexing: Accessing specific elements in an array using their position.
#### Slicing: Extracting a continuous range of elements from an array.
#### Fancy Indexing: Selecting multiple arbitrary elements using a list or array of indices.
#### Boolean Masking: Selecting elements that meet a condition using True/False filtering.

##### 1.Indexing
##### Syntax: array_name[index of array(0 to n)]


In [2]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5,6])
print(arr[0])  # Accessing the first element
print(arr[2])  # Accessing the third element
print(arr[-1]) # Accessing the last element

1
3
6


##### Indexing in 2D array

In [7]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)
print(arr_2d[0, 1])  # Accessing element at first row, second column
print(arr_2d[1, 2])  # Accessing element at third row, third column
print(arr_2d[2, 0])  # Accessing element at second row, first column


[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
6
7


##### Indexing in 3D array

In [9]:
arr_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr_3d)
print(arr_3d[0, 1, 0])  # Accessing element at first block, second row, first column 3
print(arr_3d[0, 0, 1])  # Accessing element at first block, first row, second column 2
print(arr_3d[1, 0, 1])  # Accessing element at second block, first row, second column 6
print(arr_3d[1, 1, 1])  # Accessing element at second block, second row, second column 8

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
2
6
8


#### 2. Slicing
##### Syntax: array_name(start, stop, skip/jump/step)

In [ ]:
arr_slice = np.array([1, 2, 3, 4, 5])
print("Original array: ", arr_slice)
print(arr_slice[1:4])  # Slicing from index 1 to 3
print(arr_slice[:3])   # Slicing from start to index 2
print(arr_slice[2:])   # Slicing from index 2 to end
print(arr_slice[::2])  # Slicing with a step of 2
print(arr_slice[1:5:2]) # Slicing from index 1 to 4 with a step of 2
#negative slicing
print(arr_slice[-4:-1])  # Slicing from index -4 to -2
print("Reverse of the above array: ", arr_slice[::-1])   # Reversing the array using slicing

Original array:  [1 2 3 4 5]
[2 3 4]
[1 2 3]
[3 4 5]
[1 3 5]
[2 4]
[2 3 4]
Reverse of the above array:  [5 4 3 2 1]
[5 4 3 2 1]


#### Fancy Indexing
##### syntax: array_name[[index1, index2, index3.....]]

In [13]:
arr1 = np.array([10, 20, 30, 40, 50])
print(arr1[[0, 2, 4]])  # Accessing elements at index 0, 2, and 4

[10 30 50]


#### Boolean Masking
##### syntax: array_name[condition]

In [14]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[arr > 25])

[30 40 50]
