### Reshaping in array: changing dimentions of an array
#### View of array: Creates a new array object that shares the same data as the original — changing one will affect the other.
#### Copy of array: Creates a completely independent array — changes in one do not affect the other.

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6])
arr_2d = arr.reshape(2, 3)
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [2]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Reshape 2D to 1D
arr_1d = arr.reshape(6)

print(arr_1d)

[1 2 3 4 5 6]


#### Flattening array: 
#### 1. ravel() --> returns a view of array (affects the original array)
#### 2. flatten() --> returns a copy of array (does not affect the original array)
#### both of these help in converting and n-dimentional array into a 1-dimentional array

In [7]:
arr_2d = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr_2d.ravel())
print(arr_2d.flatten())
print(arr_2d)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
